[package]
name = "rel_util"
version = "0.1.0"
edition = "2021"

[dependencies.mischief]
version = "0.1"
path = "../mischief"
default-features = false

[dependencies.ptr_meta]
version = "0.2"
default-features = false
