name: GitHub pages

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  update:
    name: Update
    if: github.repository == 'rkyv/rel'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build book
        run: mdbook build -d public

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build crate docs
        run: cargo doc --target-dir crate_docs

      - run: mv crate_docs/doc public/docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          cname: rel.rkyv.org
